name: Build and Test

on:
  workflow_dispatch:
  push:
    branches: [ dev ]
    paths-ignore:
      - "**.md"
      - ".editorconfig"
      - '**/*.gitignore'
      - '**/*.gitattributes'
      - '**/*.yml'
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]  # Only run when PR is created or updated

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    if: github.event_name != 'push' || github.event.pull_request == null  # Prevents duplicate runs

    steps:
      # uses GitHub's checkout action to checkout code form the release branch
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      # sets up .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4.3.1
        with:
          global-json-file: ./global.json

      - name: Install WASM workload
        run: dotnet workload install wasm-tools
  
      - name: Restore dependencies
        run: dotnet restore src/aboutme.sln

      - name: Build Solution
        run: dotnet build src/aboutme.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test src/aboutme.sln --configuration Release --no-build
