name: "Publish application"
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    # env:
    #   DOTNET_NOLOGO: true
    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Install .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x
          include-prerelease: true

      # Run tests
      - name: Test
        run: dotnet test

      # Generate the website
      - name: Publish
        run: dotnet publish aboutme.wasm/aboutme.wasm.csproj -c Release -o release --nologo

      # - name: Cache buster
      #   run: |
      #     dotnet tool install --global Meziantou.Framework.Html.Tool
      #     index.html append-version --file-pattern "OnlineTools/bin/Release/net6.0/publish/wwwroot/**/*.html"

      # Publish the website
      - name: GitHub Pages action
        if: ${{ github.ref == 'refs/heads/main' }} # Publish only when the push is on main
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.PUBLISH_TOKEN }}
          publish_branch: gh-pages
          publish_dir: aboutme.wasm/bin/Release/net6.0/publish/wwwroot
          allow_empty_commit: false
          keep_files: false
          force_orphan: true
          cname: bondcodes.com
