name: "Publish application"
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Install .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.x
          include-prerelease: true

      # Run tests
      - name: Test
        run: dotnet test

      # Generate the website
      - name: Publish
        run: dotnet publish aboutme.wasm/aboutme.wasm.csproj -c Release -o release --nologo

      # Publish the website
      - name: GitHub Pages action
        if: ${{ github.ref == 'refs/heads/main' }} # Publish only when the push is on main
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.PUBLISH_TOKEN }}
          publish_branch: gh-pages
          publish_dir: release/wwwroot
          allow_empty_commit: false
          keep_files: false
          force_orphan: true
          cname: bondcodes.com
